services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "timetrackwebdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: backend
    restart: always
    environment:
      DB_HOST: "localhost"
      DB_USER: "postgres"
      DB_PASSWORD: "qwerty"
      DB_NAME: "timetrackwebdb"
    ports:
      - "1828:1828"
    depends_on:
      - postgres

  frontend:
    build: ./client
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
